<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KULDEEPIT-PC" ignored="0" name="Default test(failed)" tests="4" failures="2" timestamp="05 Sep 2017 06:27:55 GMT" time="0.064" errors="0">
  <testcase name="textGenX" time="0.015" classname="testNG_practice.FaildTestCases">
    <skipped/>
  </testcase> <!-- textGenX -->
  <testcase name="textGenX" time="0.001" classname="testNG_practice.FaildTestCases">
    <failure type="java.lang.AssertionError" message="expected [JamesFail] but found [james]">
      <![CDATA[java.lang.AssertionError: expected [JamesFail] but found [james]
	at testNG_practice.FaildTestCases.textGenX(FaildTestCases.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- textGenX -->
  <testcase name="testGenY" time="0.002" classname="testNG_practice.FaildTestCases">
    <skipped/>
  </testcase> <!-- testGenY -->
  <testcase name="testGenY" time="0.002" classname="testNG_practice.FaildTestCases">
    <failure type="java.lang.AssertionError" message="expected [World] but found [hello]">
      <![CDATA[java.lang.AssertionError: expected [World] but found [hello]
	at testNG_practice.FaildTestCases.testGenY(FaildTestCases.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testGenY -->
</testsuite> <!-- Default test(failed) -->
